### ISSUE TITLE
How to access content providers using Room?

### ISSUE THREAD

**Issue by denimwho** [googlesamples/android-architecture-components#13]
One of the most common content provider that is accessed is Android's MediaStore. How do I access data of  Android MediaStore using Room?

**Comment by yigit** [comment]
Unfortunately no. Room is designed to work with SQLite database.

**Comment by gajicm93** [comment]
Room is not meant for it, but I was wondering the same thing regarding the Live Data. Could you give examples how to load MediaStore/ContactsProvider with live data, instead of Loaders?

I'll be implementing this soon, and I'd like to use LiveData instead of Loaders, and of course it's also important that my LiveData gets notified of any change in the MediaStore, which somehow already works with the Loader.. @yigit Thanks!

**Comment by Lingviston** [comment]
One more thing is SyncAdapter. Of course we can update Room database directly from it and all associated LiveData objects should get the update. But what about the ContentProvider instances connected to the same SQLite db? What to do with ContentProviderClient, which is passed into a SyncAdapter instance?

**Comment by bpappin** [comment]
I[m int he same boat @Lingviston is. I'm migrating to Room, but without a content provider, the sync engine won't run.

**Comment by Lingviston** [comment]
@bpappin it is generally OK, because Room is not a replacement for ContentProviders. But since Room can be used by ContentProvider I think it should come with helper classes which allow avoid writing lots of boilerplate code when you need to communicate with Room DB in your own app through the CP protocol.

**Comment by KryptKode** [comment]
@gajicm93 Did you manage to implement using live data to load MediaStore/ContactsProvider?

**Comment by gajicm93** [comment]
@KryptKode I think I didn't end up trying it, but if you need it, I would recommend to start by looking into Room generated code to see how they convert SQL queries into LiveData, and write the same code manually for MediaStore. If you need any additional help just send me a message.

![Screen Shot 2019-08-15 at 15 55 53](https://user-images.githubusercontent.com/9215497/63099550-9269d900-bf75-11e9-9de1-684b69aefb6b.png)

**Comment by vyadav33e** [comment]
> Unfortunately no. Room is designed to work with SQLite database.

So Room cannot be used with content providers like call logs,contacts etc?

**Comment by KryptKode** [comment]
Yes @vyadav33e

**Comment by ahmadtahir1919** [comment]
I have two Application, Application A is main App and Application B is child Application i have database in Application A(main app) now i want to use Application A database into Application B and use all data in Application B i found some answers but all answers are SQLite with ContentProvider but not for Room and no any example found.
