### ISSUE TITLE
PagingWithNetworkSample - failed loading new data when Internet connection enabled

### ISSUE THREAD

**Issue by daimonkor** [googlesamples/android-architecture-components#248]
Please check retrofit request.
Step by step:
1. open application
2. scroll to bottom and waiting loading new page data
3. turn off mobile data
4. scroll to bottom and waiting display retry button
5. click retry and waiting display retry view (it is normal state)
6. turn on mobile data
7. click retry again and displayed retry view again (why)

Observed: Internet connection is available, but I see retry view
Expected: loading new page data   

Please look [video](https://www.dropbox.com/s/67vytebbf9yb2z2/device-2017-12-11-211032.mp4?dl=0). Thanks for your support.

**Comment by yigit** [comment]
looks like requests are timing out, not necessarily related to paging.
I was having a similar problem during development in the emulator. For some reason, it was still not giving network access to the app. Instead of using quick settings, it helped to modify it from settings network page. This might be an emulator bug or maybe we are not setting up retrofit properly in the demo.

**Comment by daimonkor** [comment]
When I turned on mobile data, youtube loaded data, please look last video seconds.
