### ISSUE TITLE
How to apply latest Paging loading mechanism with GithubBrowserSample?

### ISSUE THREAD

**Issue by b95505017** [googlesamples/android-architecture-components#252]
GithubBrowserSample combine with network and database, which should use `BoundaryCallback` when migrating to new Paging loading mechanism, and it only feed the last item when reaching end, but github API only use page number when querying next page.
How do I use last item to query next github page?

**Comment by nishant304** [comment]
BoundaryCallbcak is tightly coupled with Items, and items should not care about position or page number. I cant think of a solution other than changing the api or store required info in Items(seems a really bad approach to me). Were you able to solve this problem?

**Comment by droidpl** [comment]
I find the same issue with it. Posted it on stackoverflow https://stackoverflow.com/questions/50456919/paging-library-boundary-callback-for-network-db-with-api-taking-page-and-siz. If someone managed to solve it please give some insights.

**Comment by ChrisCraik** [comment]
There are a few different options for how to use a BoundaryCallback:

1) Api uses key from within item, just use item passed to BoundaryCallback. This is what we do in the samples, and it's the easiest approach if your network api allows it.

2) Api uses page key/page index. The Paging library doesn't know about the page key or page index from the BoundaryCallback, so you need to track it yourself. It's not stored in the query that the Paging library is loading from, but there are two ways to handle it:

2a) Store the key in memory, inside your BoundaryCallback, and trigger a refresh when you start paging. Often it doesn't make sense to keep querying page after page from network if your process has died, and is restarted many hours or days later. The Paging codelab stores it in memory: https://codelabs.developers.google.com/codelabs/android-paging/index.html#8 though it doesn't implement the refresh on launch.

2b) Store the key in local storage, so you can resume your query if the process dies, or if you restart your paging stream from local storage. With a positional / page index api, there's a simple way to do this: e.g. githubService.loadPage(listSize / NETWORK_PAGE_SIZE).

Paging doesn't pass currentListSize to the boundaryCallback, though. That's because the library doesn't necessarily know the number of items in local storage (since you can disable placeholders, or a DataSource can choose not to count the number of items). In practice, you can just do:

    runOnDbThread {
        int listSize = countItems()
        runOnNetworkThread {
            githubService.loadPage(listSize / NETWORK_PAGE_SIZE);
        }
    }

If you're using page keys though, and want to resume a paged query without refreshing, the only option is to store the current page key.

Let me know if this makes sense, and I'll add this explanation to the docs.

**Comment by droidpl** [comment]
Thanks Chris for your answer. I understand your point, and indeed, it would be nice to add this to the documentation. I believe that storing the last loaded page on preferences or similar would do the trick, but still sounds a bit dirty to me.

Would it be useful to pass to the boundary callback some context information of the query more than the item? Some info like:
- How many pages the PagedList has loaded from the data source
- if the last page was fully loaded

Is there some technical implication of passing that to the boundary callback? I think that information in many cases will solve the issue, and you will not need to do any calculation on the size, it's more about how many things have been requested to the data source right?

Let me know your thoughts.

**Comment by ChrisCraik** [comment]
To me, the primary dirtiness of persisting the page key is in resuming a paged network query after process death, potentially after a long period of time. If you're comfortable with resuming that query though, storing it in the DB or similar is quite reasonable.

Paging only ever call the BoundaryCallback.onItemAtEndLoaded if the last page is fully loaded, so that's always true (and I can clarify that in docs as well)

The reason we don't pass anything else is that we don't want to pass information that looks safe, but sometimes isn't, e.g.:

* We don't pass you page count, since the page size loaded from the DataSource is often different from network page size. E.g. 10 pages of 50 items loaded from the network, but that's just 5 pages of 100 items from DB, page count isn't useful. You can try and make them the same, but you can hit cases where (especially network) paged APIs silently coerce your page size to some maximum value.

* We don't pass number of items loaded, because we may not have loaded all data from position 0, or we may have dropped pages due to a DB side change, which makes us requery the DB.

**Comment by droidpl** [comment]
Got it, makes sense. Still for case 1 I think it can be useful even if the paging is not the same, as your caching logic may or may not be dependent on the number of pages, and at the and you can always do some sort of calculations based on items loaded in database to items you want to load from the network. I think it would be a nice addition, although I understand if you don't want to add it.

For now, I will go with shared prefs and last loaded page stored there, as in my case it fits, thanks for your help.

**Comment by ChrisCraik** [comment]
Thanks for the questions, I copied much of the above information to the docs, should go out with androidx Paging docs.

And yes, it could be useful in some cases to pass that information, but we'd still prefer to not pass information that may not be safe. E.g. your boundarycallback network paging could be broken when someone changes the DB PagedList.Config (page size or placeholders)

**Comment by q464pp** [comment]
可以拉取請求合併嗎謝謝
