### ISSUE TITLE
What about backPressure ?

### ISSUE THREAD

**Issue by EMIN3M1986** [googlesamples/android-architecture-components#270]
It is very good component, but what about backPressure (like RxJava)?
Imagine we have a chat App that arrives a lot of message in a second. The list should be sorted and Updated for example each 10 millisecond or less. It's make UI laggy, but with backPressure support we can update the model and update the UI each for example 1 second. 
At the end I have to say It seems the best architecture component that I ever seen.
Thanks.﻿

**Comment by iammert** [comment]
How about LiveDataReactiveStreams? Actually I don't want architecture components which has RxJava internally. You can easily convert your Flowable to LiveData. You can support backpressure in your reactive flowable and convert your publisher to LiveData with LiveDataReactiveStreams.

**Comment by yigit** [comment]
Unlikle Rx, LiveData **is not** a stream. It is more like a subject, which only keeps the last data posted, so you cannot use it to dispatch chat messages. (because you may lose messages if more than one comes in 1 frame). 
LiveData is designed to represent the state of UI along w/ a ViewModel. So if it is a chat UI, it should represent the list of messages.
For a case like a growing list, we already provide the paging library, which you may want to take a look at.
