### ISSUE TITLE
Could not allocate CursorWindow in room

### ISSUE THREAD

**Issue by mchenani** [googlesamples/android-architecture-components#289]
Hi, I'm using room in a big application (messaging application) and when a conversation auto download images is enabled, I got this error:
Could not allocate CursorWindow [my db name] of size 2097152 due to error -12.
error while executing job ...DownloadMultimediaJob@3977b039
                                                   android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
                                                       at android.database.CursorWindow.<init>(CursorWindow.java:108)

**Comment by magdamiu** [comment]
Hi! The idea is that the CursorWindows has maximum 2mb so in this case for that query in order to get some consistant data you sould annotated your Dao method with @Transaction.

**Comment by crossle** [comment]
Same problem `android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)`

**Comment by ChrisCraik** [comment]
The exception means your process can't allocate a 2MB buffer. This usually indicates a memory leak, and it's happening with cursor because when you're nearly out of memory, a big cursor allocation is more likely to fail than some tiny other object.

If you can reproduce this locally, try and take a snapshot of memory state, and see if anything looks like a leak: https://developer.android.com/studio/profile/am-memory.html#snapshot

For the future, this issue tracker is for issues with the samples. To open an issue against the libraries themselves, please use: https://issuetracker.google.com/issues/new?component=197448&template=878802 (which is linked in the d.android.com top level pages for arch components)

Thanks
