### ISSUE TITLE
PagingWithNetwork: loadAfter() not working correctly after invalidate() is called

### ISSUE THREAD

**Issue by damiafuentes** [googlesamples/android-architecture-components#379]
Using the `PagingWithNetwork` and `Network only (by page)`. Change the `pageSize` to 1 or 2 in `SubRedditViewModel`. Then, after a swipe-to-refresh (so `invalidate()` is called) the `loadAfter()` method is not called anymore. Any recommendation to avoid this?

(I am having same behavior in my app with a higher page size)

**Comment by tententen2** [comment]
me too

**Comment by LanderlYoung** [comment]
You probably used the `LivePagedListBuilder` class, which try to used the `mList.getLastKey()` for your new `PagedList`.
More detail on `LivePagedListBuilder.create` method.

And IMHO there should be an option to switch off the "inherit the last key" behavior.

**Comment by shin-dongkyu** [comment]
Same issue...

Did you solve this problem?

**Comment by VongVia1209** [comment]
This problem because your refreshed  data is same old data ,cause adapter don't perform getItem(),so it can't perform loadAround() to  loadAfter().

**Comment by shaolizhi1234** [comment]
me too

**Comment by shaolizhi1234** [comment]
My solution is - call each time before refreshing:
adapter.submitList (empty)
Then use:
Datasource.invalidate()

**Comment by VongVia1209** [comment]
> My solution is each time before refreshing, call:
> `adapter.submitList(null)`
> Then use:
> `datasource.invalidate()`
> 
> but it was ugly...

if u do this  the DiffUtil will be useless ,the adapter refresh is low efficiency

**Comment by ChrisCraik** [comment]
This issue was also filed in the library bug tracker as https://issuetracker.google.com/issues/113122599

> This problem because your refreshed data is same to old data ,cause adapter don't perform getItem(), so it can't perform loadAround() and loadAfter().

To add more detail here, it's because the initial load size fits within the viewport, and nothing changed. If the adapter sees nothing changed in viewport and the user can't scroll, there's nothing to trigger further loads.

We put in a sort of workaround in 2.1.0 (alpha), but as said in the bug and release notes, the real fix is having a large enough initial load size. The initial load size defaults to 3x page size - change your initial load size to be larger (with `Config.Builder.setInitialLoadSizeHint()`), and the problem will go away.
