### ISSUE TITLE
AndroidViewModel not destroyed when activity is destroyed..

### ISSUE THREAD

**Issue by AagitoEx** [googlesamples/android-architecture-components#468]
I recently observed this issue (or by design).. that the Subclasses of AndroidViewModel is not destroyed even when the host activity is destroyed. It simply re-attaches itself with the activity if the activity is created again, still retaining old data.
Is this because AndroidViewModel holds the reference to application context or is this just a bad behavior.
Even if this is by design, I am having problems managing my activity's state as i need the application context for RoomDB. Can anyone please confirm this issue.

And I am not sure where to report this issue. So I just posted it here.

'androidx.appcompat:appcompat:1.0.0'
"androidx.lifecycle:lifecycle-extensions:2.0.0"
"androidx.lifecycle.AndroidViewModel"

@florina-muntenescu

**Comment by itscorey** [comment]
I think this is because it is *Application context aware*.

Also, you do not need to init Room in your ViewModel. You can make yours DAOs as dependencies of your ViewModel, then you inject them using a `ViewModel.Factory` or you can use a framework.

About initializing Room... another class can be responsible for it.
