### ISSUE TITLE
GithubBrowserSample with Java

### ISSUE THREAD

**Issue by mynormeza** [googlesamples/android-architecture-components#491]
Is there any way you can provide a GithubBrowserSample version for Java. I have 0 knowledge of Kotlin and I find the content of this repo really useful for practice.

**Comment by ChrisCraik** [comment]
You can checkout the version prior to the Kotlin conversion:

`git checkout b1a194c1ae267258cd002e2e1c102df7180be473`

Or look at it on online: https://github.com/googlesamples/android-architecture-components/tree/b1a194c1ae267258cd002e2e1c102df7180be473

There have been improvements and changes since then, but we don't plan to maintain a Java version of that sample going forward.

**Comment by Hoss3inf** [comment]
well, this is the last commit before the vast migration to kotlin, it might not be awesome, but at least it has some taste of java. first, clone the repository, then:
`git checkout b1a194c1ae267258cd002e2e1c102df7180be473`
